cc: clang
cc_asm: clang-unwrapped
target: ci

xdsl-opt-backend-passes:
  - scf-for-loop-unroll
  - convert-vector-to-ptr
  - convert-memref-to-ptr{lower_func=true}
  - convert-ptr-type-offsets
  - canonicalize
  - convert-func-to-x86-func
  - convert-vector-to-x86{arch=avx512}
  - convert-ptr-to-x86{arch=avx512}
  - convert-arith-to-x86
  - reconcile-unrealized-casts
  - canonicalize
  - x86-infer-broadcast
  - dce
  - x86-allocate-registers
  - canonicalize

libxsmm-gemm-passes:
  - x86-prologue-epilogue-insertion

compxsmm-gemm-passes:
  - xsmm-tile-n{disable-regalloc=true}
  - xsmm-matmul-n-to-m
  - xsmm-tile-m{disable-regalloc=true}
  - xsmm-matmul-m-to-k
  - xsmm-tile-k{disable-regalloc=true}
  - convert-xsmm-to-x86{disable-regalloc=true}
  - x86-regalloc-verify-liveness
  - x86-allocate-registers
  - convert-x86-scf-to-x86
  - x86-prologue-epilogue-insertion

targets:
  neon: {
    triple: "arm64-apple-darwin",
    arch: "armv8.5-a",
    freq: 1.0,
    peak_f32: 0,
    libs: [],
    linker_flag: "",
    env: {}
  }
  ci: {
    triple: "x86_64-unknown-linux-gnu",
    arch: "x86-64",
    freq: 1.0,
    peak_f32: 0,
    libs: [],
    linker_flag: "-fuse-ld=lld",
    env: {}
  }
  tower: {
    triple: "x86_64-unknown-linux-gnu",
    arch: "znver5",
    freq: 4.3,
    peak_f32: 64,
    libs: ["papi"],
    linker_flag: "-fuse-ld=lld",
    env: {"LIBPFM_FORCE_PMU":"amd64"}
  }
  pinocchio: {
    triple: "x86_64-unknown-linux-gnu",
    arch: "cascadelake",
    freq: 2.1,
    peak_f32: 64,
    libs: ["papi"],
    linker_flag: "-fuse-ld=lld",
    env: {}
  }

xsmm_map: {cascadelake: clx, znver5: skx, default: noarch}
