[project]
name = "autotuner"
version = "0.1.0"
description = "Benchmarks repository for xDSL autotuning paper."
readme = "README.md"
requires-python = ">=3.11.2"
dependencies = ["snakemake>=8.30.0", "xdsl[dev]>=0.29.0"]

[project.scripts]
hello = "autotuner.main:main"

[tool.setuptools]
package-dir = { "autotuner" = "src" }
packages = ["autotuner"]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pyright]
include = ["src"]
