[project]
name = "autotuner"
version = "0.1.0"
description = "Benchmarks repository for xDSL autotuning paper."
readme = "README.md"
requires-python = ">=3.11.2,<3.13"
dependencies = [
    "jinja2>=3.1.6",
    "lighthouse",
    "matplotlib>=3.10.3",
    "pandas>=2.3.1",
    "snakemake>=8.30.0",
    "tvm==0.19.0.2025010903",
    "xdsl[dev]",
]

[project.entry-points.'xdsl.universe']
autotuner = 'autotuner.universe:AUTOTUNER_UNIVERSE'

[[tool.uv.index]]
name = "corse"
url = "https://gitlab.inria.fr/api/v4/groups/corse/-/packages/pypi/simple"
explicit = true

[[tool.uv.index]]
name = "eudsl"
url = "https://llvm.github.io/eudsl"
explicit = true
format = "flat"

[tool.uv.sources]
xdsl = { git = "https://github.com/xdslproject/xdsl.git", rev = "5ef95a7932e18786c043a6e1237c84ac42716ab2" }
tvm = { index = "corse" }
lighthouse = { git = "https://github.com/llvm/lighthouse.git", rev = "455d61cf60b2b553d545783bcb5258d4cf50fe03" }
mlir-python-bindings = { index = "eudsl" }

[project.scripts]
hello = "autotuner.main:main"
plot-ttile = "autotuner.plot_ttile:main"
plot-ttile-squares = "autotuner.plot_ttile_squares:main"
plot-ttile-combined = "autotuner.plot_ttile_combined:main"
plot-cube = "autotuner.plot_cube:main"
plot-heatmap = "autotuner.plot_heatmap:main"
libxsmm-gemm = "autotuner.libxsmm_gemm.libxsmm_generator_gemm_driver:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/autotuner"]

[tool.pyright]
include = ["src", "tests"]
