# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI - Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Cache uv packages
      uses: actions/cache@v5
      with:
        path: ~/.cache/uv
        key: uv-nix-${{ hashFiles('uv.lock') }}
        restore-keys: uv-nix-
    - name: Run tests
      run: nix develop --command make tests
    - name: Prune uv cache
      run: nix develop --command uv cache prune --ci
